import Topbar from "@/components/nav/Topbar";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <div className="flex flex-col min-h-screen">
          <div className="py-2 transition-colors bg-green-100 text-green-700 relative z-20 text-center">
            <div className="gap-4 justify-center lg:justify-center items-center lg:items-center flex flex-wrap">
              <span className="text-xs font-light text-center md:text-center">
                Free shipping on orders over $39 | Excludes AK, HI, & PR
              </span>
            </div>
          </div>
          <Topbar />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
